
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package com.pacheco.mee_3;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int POW = 7;
  public static final int NUMBER = 2;
  public static final int MULT = 5;
  public static final int C_BRACKET = 9;
  public static final int EOF = 0;
  public static final int ADD = 3;
  public static final int DIV = 6;
  public static final int O_BRACKET = 8;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "ADD",
  "MINUS",
  "MULT",
  "DIV",
  "POW",
  "O_BRACKET",
  "C_BRACKET"
  };
}

